### ISSUE TITLE
Uncaught Error: uniform location for u_resolution not found

### ISSUE THREAD

**Issue by Hukir** [davidpaulrosser/atom-glsl-preview#51]
Hey floks,

Getting this error and impossible to olad uniform u_resolution.
Works on other machinebut not this one...

Any cues?

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.35.1 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.12.5
**Thrown From**: [glsl-preview](https://github.com/fordhurley/atom-glsl-preview) package 2.0.0

### Stack Trace

Uncaught Error: uniform location for u_resolution not found

**Comment by fordhurley** [comment]
My understanding is that your shader had

```
uniform vec2 u_resolution;
```

but you never used `u_resolution` in the shader itself.

If that's the issue, I've been meaning to push a fix for that for a little while. Can you update to 2.0.1 and try again?

Otherwise, please reopen this issue and provide the shader you were trying to run!

**Comment by Hukir** [comment]
Seems good!

What a powerful community!

This is amazing speed thank you sir!!





Le jeu. 4 avr. 2019 à 11:59, Ford Hurley <notifications@github.com> a
écrit :
